apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donggu-pf-tomcat-hpa
  namespace: donggu-pf
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: donggu-pf-tomcat
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70