apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donggu-pf-nginx
  namespace: donggu-pf
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: donggu-pf-nginx
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70